### ISSUE TITLE
Sorting by pk as in the example throws `Cannot use None as a query value`

### ISSUE THREAD

**Issue by gabriel119435** [nitely/django-infinite-scroll-pagination#12]
there's this example on the docs:

    page = paginator.paginate(queryset, lookup_field='pk', value=pk, per_page=20)
but since paginator.paginate is actually

    def paginate(query_set, per_page, lookup_field, value, pk=None, move_to=NEXT_PAGE):
        ...
        .page(
            value=value,
            pk=pk,
            move_to=move_to))

`None` is passed to `page`, which causes it build this query

    ...WHERE ("anyModel"."id" >= someValue AND NOT ("anyModel"."id" = someValue AND NOT ("anyModel"."id" > None)))...
causing 

        raise ValueError("Cannot use None as a query value")
    ValueError: Cannot use None as a query value

instead of just `...WHERE "anyModel"."id" > someValue...`

I believe removing `pk=None` from `paginate` would cause `def page(self, value, pk=_NO_PK, move_to=NEXT_PAGE)` to use its default value `_NO_PK`, creating the last query correctly

**Comment by gabriel119435** [comment]
if my understanding is wrong, could you please elaborate more on cited example with a `BaseModel` and actual values with the corresponding SQL?

**Comment by nitely** [comment]
It should be fixed on v1.2.1
Thanks for reporting this
