### ISSUE TITLE
) is missing in the doc

### ISSUE THREAD

**Issue by Kifsif** [nitely/django-infinite-scroll-pagination#7]
It seems that there is a bug in the documentation.

https://github.com/nitely/django-infinite-scroll-pagination#performance

Wrong:

    class Meta:
        indexes = [
            models.Index(fields=['created_at', 'pk'],
            models.Index(fields=['-created_at', '-pk'])]

IMHO should be:

        indexes = [
                models.Index(fields=['created_at', 'pk']),
                models.Index(fields=['-created_at', '-pk'])]

Thta is a ) is missing.

**Comment by nitely** [comment]
Fixed in #8
